services:
  develop:
    container_name: tempalte_base02_develop
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    ports:
      - "8270:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    env_file:
      - ./env/prod.env
    command: sh -c "npm run build && npm run start"
