services:
  develop:
    container_name: tempalte_base02_develop
    ports:
      - "8270:3000"
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    working_dir: /app
    env_file:
      - ${ENV_FILE:-./env/prod.env}
    command: npm run start
    volumes:
      # ソースコードはホストと同期
      - ./frontend:/app
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=768"
    mem_limit: 1g
